name: Main workflow

on:
  pull_request:
  push:
  schedule:
    - cron: 0 1 * * MON

jobs:
  Tests:
    strategy:
      fail-fast: false
      matrix:
        # We test:
        # - once for each architecture with the latest OCaml
        # - once for a few older versions of OCaml under Linux
        ocaml-compiler:
          - 4.13.1
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest
        include:
          - ocaml-compiler: 4.10.0
            os: ubuntu-latest
          - ocaml-compiler: 4.09.1
            os: ubuntu-latest
          - ocaml-compiler: 4.08.1
            os: ubuntu-latest
          - ocaml-compiler: 4.05.0
            os: ubuntu-latest

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup OCaml ${{ matrix.ocaml-version }}
        uses: ocaml/setup-ocaml@v2
        with:
          cache-prefix: v1-${{ matrix.os }}-${{ matrix.ocaml-compiler }}
          dune-cache: true
          ocaml-compiler: ${{ matrix.ocaml-compiler }}

      - name: Build dependencies
        run: opam exec -- ocaml .github/workflows/ci.ml build

      - name: Run test suite
        run: opam exec -- ocaml .github/workflows/ci.ml test

  Format:
    strategy:
      matrix:
        include:
         - ocaml-compiler: 4.13.1
           os: ubuntu-latest

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup OCaml ${{ matrix.ocaml-compiler }}
        uses: ocaml/setup-ocaml@v2
        with:
          cache-prefix: v1-${{ matrix.os }}-${{ matrix.ocaml-compiler }}
          dune-cache: true
          ocaml-compiler: ${{ matrix.ocaml-compiler }}

      - name: Check that source is well formatted
        uses: ocaml/setup-ocaml/lint-fmt@v2
